import { describe, expect, it } from 'vitest'

import {
  wagmigotchiContractConfig,
  mlootContractConfig,
  renderComposable
} from '../../../test'
import { useContractRead } from './useContractRead'

describe('useContractRead', () => {
  it('mounts', async () => {
    const { result, waitFor } = renderComposable(() =>
      useContractRead({
        ...wagmigotchiContractConfig,
        functionName: 'love',
        args: '0x27a69ffba1e939ddcfecc8c7e0f967b872bac65c',
      }),
    )

    await waitFor(() => result.isSuccess.value)

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { internal, ...res } = result
    expect(res).toMatchInlineSnapshot(`
      {
        "data": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "data",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "error": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "error",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "errorUpdateCount": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "errorUpdateCount",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "fetchStatus": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "fetchStatus",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "isError": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "isError",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "isFetched": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "isFetched",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "isFetching": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "isFetching",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "isLoading": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "isLoading",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "isRefetching": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "isRefetching",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "isSuccess": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "isSuccess",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "refetch": [Function],
        "status": ObjectRefImpl {
          "__v_isRef": true,
          "_defaultValue": undefined,
          "_key": "status",
          "_object": {
            "data": [Function],
            "dataUpdatedAt": 1663053732432,
            "error": null,
            "errorUpdateCount": 0,
            "errorUpdatedAt": 0,
            "failureCount": 0,
            "fetchStatus": "idle",
            "isError": false,
            "isFetched": true,
            "isFetchedAfterMount": true,
            "isFetching": false,
            "isLoading": false,
            "isLoadingError": false,
            "isPaused": false,
            "isPlaceholderData": false,
            "isPreviousData": false,
            "isRefetchError": false,
            "isRefetching": false,
            "isStale": true,
            "isSuccess": true,
            "refetch": [Function],
            "remove": [Function],
            "status": "success",
          },
        },
        "suspense": [Function],
      }
    `)
  })

  describe('configuration', () => {
    it('chainId', async () => {
      const { result, waitFor } = renderComposable(() =>
        useContractRead({
          ...wagmigotchiContractConfig,
          functionName: 'love',
          args: '0x27a69ffba1e939ddcfecc8c7e0f967b872bac65c',
          chainId: 1,
        }),
      )

      await waitFor(() => result.isSuccess.value)

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { internal, ...res } = result
      expect(res).toMatchInlineSnapshot(`
        {
          "data": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "data",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "error": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "error",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "errorUpdateCount": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "errorUpdateCount",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "fetchStatus": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "fetchStatus",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isError": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isError",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isFetched": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isFetched",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isFetching": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isFetching",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isLoading": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isLoading",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isRefetching": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isRefetching",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isSuccess": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isSuccess",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "refetch": [Function],
          "status": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "status",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053732510,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "suspense": [Function],
        }
      `)
    })

    it('enabled', async () => {
      const { result, waitFor } = renderComposable(() =>
        useContractRead({
          ...wagmigotchiContractConfig,
          functionName: 'love',
          enabled: false,
        }),
      )

      await waitFor(() => result.status === 'idle')

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { internal, ...res } = result
      expect(res).toMatchInlineSnapshot(`
        {
          "data": undefined,
          "error": null,
          "fetchStatus": "idle",
          "isError": false,
          "isFetched": false,
          "isFetching": false,
          "isIdle": true,
          "isLoading": false,
          "isRefetching": false,
          "isSuccess": false,
          "refetch": [Function],
          "status": "idle",
        }
      `)
    })
  })

  describe('return value', () => {
    it('refetch', async () => {
      const { result } = renderComposable(() =>
        useContractRead({
          ...wagmigotchiContractConfig,
          functionName: 'love',
          args: '0x27a69ffba1e939ddcfecc8c7e0f967b872bac65c',
          enabled: false,
        }),
      )

      ;(async () => {
        const { data } = await result.refetch()
        expect(data).toMatchInlineSnapshot('[Function]')
      })()
    })
  })

  describe('behavior', () => {
    it('can use multiple args', async () => {
      const { result, waitFor } = renderComposable(() =>
        useContractRead({
          ...mlootContractConfig,
          functionName: 'tokenOfOwnerByIndex',
          args: ['0xA0Cf798816D4b9b9866b5330EEa46a18382f251e', 0],
        }),
      )

      await waitFor(() => result.isSuccess.value)

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { internal, ...res } = result
      expect(res).toMatchInlineSnapshot(`
        {
          "data": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "data",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "error": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "error",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "errorUpdateCount": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "errorUpdateCount",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "fetchStatus": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "fetchStatus",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isError": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isError",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isFetched": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isFetched",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isFetching": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isFetching",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isLoading": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isLoading",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isRefetching": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isRefetching",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "isSuccess": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "isSuccess",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "refetch": [Function],
          "status": ObjectRefImpl {
            "__v_isRef": true,
            "_defaultValue": undefined,
            "_key": "status",
            "_object": {
              "data": [Function],
              "dataUpdatedAt": 1663053737622,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "failureCount": 0,
              "fetchStatus": "idle",
              "isError": false,
              "isFetched": true,
              "isFetchedAfterMount": true,
              "isFetching": false,
              "isLoading": false,
              "isLoadingError": false,
              "isPaused": false,
              "isPlaceholderData": false,
              "isPreviousData": false,
              "isRefetchError": false,
              "isRefetching": false,
              "isStale": true,
              "isSuccess": true,
              "refetch": [Function],
              "remove": [Function],
              "status": "success",
            },
          },
          "suspense": [Function],
        }
      `)
    })
  })
})
